### ISSUE TITLE
bug: Crash for large lua file (with lsp configed)

### ISSUE THREAD

**Issue by mathjiajia** [folke/noice.nvim#315]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-2065ce877

### Operating system/version

macOS 13.1

### Describe the bug

When scrolling very fast in a larger lua file, nvim will crash.

### Steps To Reproduce

1. make sure `lua-language-server` is in the PATH;
2. use this repro.lua, `nvim -u repro.lua`, to install the plugins;
3. quit nvim;
4. open a large file (200 loc, say), `nvim -u repro.lua health.lua`, where `health.lua` is the file in this repo, or you make replace it with a large lua file.
5. scroll quickly.

### Expected Behavior

as normal, no crash

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	-- add any other plugins here
	{
		"neovim/nvim-lspconfig",
		config = function()
			require("lspconfig").sumneko_lua.setup({})
		end,
	},
	{
		"folke/noice.nvim",
		dependencies = { "MunifTanjim/nui.nvim" },
		config = true,
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Does this happen with the latest noice version? I fixed something for nightly half an hour ago

**Comment by mathjiajia** [comment]
Yes, even with the latest noice

**Comment by folke** [comment]
I can't reproduce this with the latest noice version and your repro. IT does crash with the version before that.

Are you 100% sure you're testing this with the latest noice version?

Make sure to delete `./.repro` to get the latets version

**Comment by mathjiajia** [comment]
> Make sure to delete `./.repro` to get the latets version

Yeah, that is what I did.

The problem is still there, as shown by the recording:

https://user-images.githubusercontent.com/35106942/212502966-5882bf00-5e06-4b30-97ac-c4d682c0a1e0.mov

**Comment by folke** [comment]
You deleted the whole directory? Including the lazy-lock.json file?

Can you double-check by opening in with `-u`, run lazy and check the commit?

**Comment by mathjiajia** [comment]
I can confirm that everything is updated.
The larger the lua file is, the easier to crash: scroll up and down very fast.

<img width="1130" alt="Screenshot 2023-01-15 at 3 59 55 PM" src="https://user-images.githubusercontent.com/35106942/212529387-1de8f2c6-2a9d-4315-83c4-03f8eb450783.png">
<img width="1555" alt="Screenshot 2023-01-15 at 4 02 04 PM" src="https://user-images.githubusercontent.com/35106942/212529469-00dcee37-9b81-4d5d-a261-0307c3e0130a.png">

**Comment by folke** [comment]
To further debug this, you'll have to generate a stacktrace for Neovim.
Build it from source and then use `coredumpctl -1 gdb`

**Comment by mathjiajia** [comment]
Sorry, is this tool available on macOS?
I didn't find it.

**Comment by folke** [comment]
Check the Neovim wiki on how you can generate a stack trace for macos

**Comment by mathjiajia** [comment]
https://gist.github.com/mathjiajia/5f757a0d4d25cf508f0c3732d65c5d7f

**Comment by folke** [comment]
That shows the default as it was before my changes.

The fix is here https://github.com/folke/noice.nvim/blob/main/lua/noice/ui/init.lua#L107

Can you post what that first ui is for you?

You are using TUI right?

**Comment by folke** [comment]
And do you have termguicolors set to true?

**Comment by mathjiajia** [comment]
> Can you post what that first ui is for you?

Sorry that I did not follow your point. Below is what I get by running `lua vim.pretty_print(vim.api.nvim_list_uis()[1])`:
<img width="638" alt="Screenshot 2023-01-16 at 10 27 48 PM" src="https://user-images.githubusercontent.com/35106942/212701430-58e5009e-9655-4b76-bf7e-6c23430e788a.png">


> You are using TUI right?

I am just using `nvim` in `kitty`.

**Comment by folke** [comment]
Does this happen with the latest nightly?

**Comment by mathjiajia** [comment]
still occurs

**Comment by al-ce** [comment]
Responding to your question in #298 about other Mac users.

NVIM v0.9.0-dev-1941+g20b7be2d1-dirty
macOs 12.5.1 Monterey

Can reproduce in:
Terminal (emulator): kitty or iTerm2 or macOs Terminal
shell: zsh or bash

I can reproduce this when scrolling with a mousewheel in large files. Scrolling very slowly does not cause the crash. Also occurs if I "scroll" fast by holding down Ctrl+D/U, but not instantly as it does with the mousewheel.

**Comment by folke** [comment]
@al-ce are you sure this is due to noice?

See also https://github.com/neovim/neovim/issues/21815

@mathjiajia can you check if the issue persists without noice?

**Comment by al-ce** [comment]
I'm not sure what all I should test to rule everything out, but here's some situations I'm trying.

Using a [minimal packer config](https://pastebin.com/B2sjL9mx), I can only reproduce the behavior if there's a Noice notification window displayed as I'm scrolling (e.g. `:lua vim.notify("hi")`, start scrolling). Otherwise, scrolling through a large file doesn't crash it.

Using the LazyVim starter config, with Noice disabled I seemingly can't reproduce the issue. With Noice enabled, it occurs whether there is a notification window displayed or not.

**Comment by mathjiajia** [comment]
> @mathjiajia can you check if the issue persists without noice?
For me, once remove either lspconfig or noice, then cannot reproduce the crash.

**Comment by folke** [comment]
Does it happen when you disable `nvim-notify`?

**Comment by folke** [comment]
What if you disable:

`config.lsp.message.enabled = false`

or

`config.lsp.progress.enabled = false`

**Comment by mathjiajia** [comment]
> Does it happen when you disable `nvim-notify`?

> What if you disable:
> 
> `config.lsp.message.enabled = false`
> 
> or
> 
> `config.lsp.progress.enabled = false`


Still crash by doing those.
Note: crash only happen when lsp is NOT ready, e.g., when `sumneko_lua` is loading workspaces.

**Comment by folke** [comment]
I just tested on Macos and I still can't reproduce this...

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "rcarriga/nvim-notify",
  -- add any other plugins here
  {
    "neovim/nvim-lspconfig",
    dependencies = {
      { "williamboman/mason.nvim", config = true },
      { "williamboman/mason-lspconfig.nvim", opts = { ensure_installed = { "sumneko_lua" } } },
    },
    config = function()
      require("lspconfig").sumneko_lua.setup({})
    end,
  },
  {
    "folke/noice.nvim",
    -- dir = "~/projects/noice.nvim",
    dependencies = { "MunifTanjim/nui.nvim" },
    config = true,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Tested with `neovim/runtime/lua/vim/lsp.lua` file

**Comment by folke** [comment]
Can you try running the test in empty directory? At least a directory without a `luarc.json` file?

**Comment by mathjiajia** [comment]
> Can you try running the test in empty directory? At least a directory without a `luarc.json` file?

You caught the point. No crash this time.

**Comment by folke** [comment]
ok, great. Can you show the contents of that file?

**Comment by folke** [comment]
I can actually reproduce it now. Even in an empty directory

**Comment by mathjiajia** [comment]
> ok, great. Can you show the contents of that file?

```json
{
    "$schema": "https://raw.githubusercontent.com/sumneko/vscode-lua/master/setting/schema.json",
    "Lua.workspace.checkThirdParty": false
}
```

I can reproduce with my own config (not `repro.lua`) even without `luarc.json file`
will try to find another minimal `repro.lua`.

**Comment by folke** [comment]
At least, I can already confirm this issue is not caused by `vim.ui_attach`. Looking into it further

**Comment by folke** [comment]
When I set noice `config.lsp.progress.enabled = false`, then I no longer have crashes. Can you doublecheck that?

Also set `config.lsp.message.enabled = false`

**Comment by fibbo** [comment]
I'm pretty sure it's not related to `noice`. I reported a similar bug here: https://github.com/nvim-telescope/telescope.nvim/issues/2331 and I start to believe it's not a telescope issue either but it allows me to trigger it. The assertions that are triggered in a debug build were:

`rbuffer.c:144` and `rbuffer.c:168` but I'm not sure what's causing them.

**Comment by mathjiajia** [comment]
> When I set noice `config.lsp.progress.enabled = false`, then I no longer have crashes. Can you doublecheck that?
> 
> Also set `config.lsp.message.enabled = false`

So wired. Still crash in a new directory with only two files: `repro.lua` and the `neovim/runtime/lua/vim/lsp.lua` file.

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	-- add any other plugins here
	{
		"neovim/nvim-lspconfig",
		config = function()
			require("lspconfig").sumneko_lua.setup({})
		end,
	},
	{
		"folke/noice.nvim",
		dependencies = { "MunifTanjim/nui.nvim" },
		opts = {
			lsp = {
				progress = { enabled = false },
				message = { enabled = false },
			},
		},
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

```

**Comment by folke** [comment]
I think @fibbo is right. There's a couple of other bug reports in Neovim with the same issue, but without Noice.

And I can confirm that the issue on macos is not caused by that bug in `vim.ui_attach` for which I created the work-around.

**Comment by mathjiajia** [comment]
Thanks.
No crash anymore.
IMO, this issue has been resolved.
