### ISSUE TITLE
[bug] `q:` throws errors

### ISSUE THREAD

**Issue by dtomvan** [folke/noice.nvim#4]
Reproduction:

```lua
require('packer').startup(function()
    use {
        'hrsh7th/nvim-cmp',
        requires = {
            'hrsh7th/cmp-cmdline',
        },
    }
    use 'MunifTanjim/nui.nvim'
    use 'rcarriga/nvim-notify'

    use {
        'folke/noice.nvim',
        event = 'VimEnter',
        config = function()
            require('noice').setup()
        end,
    }
end)
```

Then run `nvim` and press `q:`.

`:messages` output:

```
...site/pack/packer/start/nui.nvim/lua/nui/popup/border.lua:457: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
Error running notification service: ...e/pack/packer/start/nvim-notify/lua/notify/util/init.lua:78: Vim:...ker/start/nvim-notify/lua/notify/service/buffer/init.lua:104: Vim:...site/pack/packer/start/nui.nvim/lua/nui/popup/border.lua:457: E11: Invalid in command-line window; <CR> executes, CTRL-C quits...im/site/pack/packer/start/nui.nvim/lua/nui/text/init.lua:67: end_col value outside range
...im/site/pack/packer/start/nui.nvim/lua/nui/text/init.lua:67: line value outside range
Error running notification service: ...e/pack/packer/start/nvim-notify/lua/notify/util/init.lua:78: Vim:...ker/start/nvim-notify/lua/notify/service/buffer/init.lua:104: Vim:...im/site/pack/packer/start/nui.nvim/lua/nui/text/init.lua:67: line value outside range...im/site/pack/packer/start/nui.nvim/lua/nui/text/init.lua:67: end_col value outside range
...im/site/pack/packer/start/nui.nvim/lua/nui/text/init.lua:67: end_col value outside range
```

**Comment by folke** [comment]
I can't reproduce this unfortunately. Can you check with the lastest version?

**Comment by mxteries** [comment]
I get a similar error as dtomvan when entering the command-line window from command-line mode. Basically run `nvim` then type `:<CTRL-F>`. <kbd>CTRL-F</kbd> is the default keybinding, but it can be changed through `:h cedit`.

I'm on the latest version of noice.nvim and nui.nvim. I can also confirm that `q:` (and `q/`, `q?`) don't show the same error

**Comment by kaiphat** [comment]
The same

**Comment by kaiphat** [comment]
![image](https://user-images.githubusercontent.com/53742299/193618836-afe55142-27ca-438d-9ad3-d275eb495483.png)

**Comment by folke** [comment]
@mxteries I can reproduce your error. Will see for a fix. Will likely fix the related problems too.

**Comment by folke** [comment]
I just pushed a fix for @mxteries 

Can you all check if it also fixes your issues?

**Comment by dtomvan** [comment]
Sorry for the late response, will check ASAP

**Comment by folke** [comment]
If it would not be fixed, please add `{debug=true}` to your setup to get a more detailed stack trace

**Comment by dtomvan** [comment]
Closing. I guess the issue was fixed somewhere after between 2 days and 8 hours ago, or in 8aa5efd

**Comment by dtomvan** [comment]
Forgot to trigger VimEnter, thought it worked, didn't try `:`. Will confirm whether it works tomorrow.

**Comment by mxteries** [comment]
> I just pushed a fix for @mxteries
> 
> Can you all check if it also fixes your issues?

Yep <kbd>CTRL-F</kbd> works now, thanks!

**Comment by dtomvan** [comment]
`q:`, `q?`, `q/` and `<c-f>` all work.

**Comment by p00f** [comment]
I still get this.
Steps to reproduce:
1) `q:`
2) Wait a second
3) ![image](https://user-images.githubusercontent.com/36493671/194550834-6f09aed4-b620-4bdf-a4c2-654c7010caf7.png)

I'm on neovim https://github.com/neovim/neovim/commit/de47b4b9016803650117d2ce79a537b3975af2b7 and noice https://github.com/folke/noice.nvim/commit/3a23308e205f35fc2b80b93790fd3a92587d68e7

**Comment by p00f** [comment]
I'm not lazy loading noice or its dependencies

**Comment by Shougo** [comment]
Oh, it is reproduced for me...
It seems not fixed.

@folke Ping.

**Comment by folke** [comment]
@Shougo not home right now. I'll check tomorrow!

**Comment by folke** [comment]
Still can't reproduce unfortunately. I also don't see the cmdline as in your screenshot. Can you provide more details?

**Comment by Shougo** [comment]
I think you have mapped `q`.  You need to execute `iunmap q`.

**Comment by folke** [comment]
@Shougo no mapping for `q`.

When does the cmdline show for you?

I just get the cmdline-history window but don't see the cmdline. And no errors.

Can you post the errors you get from `:Noice log`?

**Comment by Shougo** [comment]
[noice.log](https://github.com/folke/noice.nvim/files/9741090/noice.log)

Please see this.

**Comment by folke** [comment]
Seems like you get E36 errors when we try to open a split. Not sure what triggers that.

Do you get the same with the default Noice config?

**Comment by Shougo** [comment]
This is my config.

```lua
  require'noice'.setup {
    cmdline = {
      enabled = true,
      icons = {
        ['/'] = { icon = '/', hl_group = 'DiagnosticWarn' },
        ['?'] = { icon = '?', hl_group = 'DiagnosticWarn' },
        [':'] = { icon = ':', hl_group = 'DiagnosticInfo', firstc = false },
      },
    },
    popupmenu = {
      enabled = false,
    },
    messages = {
      enabled = true,
    },
    routes = {
      {
        view = "split",
        filter = { min_width = 500 },
      },
    },
  }
```

**Comment by Shougo** [comment]
Oh, it does not reproduce when minimal init.vim...

**Comment by Shougo** [comment]
@dtomvan @kaiphat @p00f 

Please create the minimal config to reproduce the issue without the package managers.

**Comment by Shougo** [comment]
I have created the minimal init.vim and I cannot reproduce the problem.
So it seems config problem.

```vim
set rtp+=~/work/noice.nvim
set rtp+=~/src/nui.nvim
set rtp+=~/src/nvim-notify

set termguicolors

lua <<END
  require'noice'.setup {
    cmdline = {
      enabled = true,
      icons = {
        ['/'] = { icon = '/', hl_group = 'DiagnosticWarn' },
        ['?'] = { icon = '?', hl_group = 'DiagnosticWarn' },
        [':'] = { icon = ':', hl_group = 'DiagnosticInfo', firstc = false },
      },
    },
    popupmenu = {
      enabled = false,
    },
    messages = {
      enabled = true,
    },
    routes = {
      {
        view = "split",
        filter = { min_width = 500 },
      },
    },
  }
END
```

**Comment by folke** [comment]
I added a template to create a minimal.lua file https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by p00f** [comment]
I can't reproduce it using the minimal config 👍🏽

**Comment by dtomvan** [comment]
> I'm on neovim [neovim/neovim@de47b4b](https://github.com/neovim/neovim/commit/de47b4b9016803650117d2ce79a537b3975af2b7) and noice [3a23308](https://github.com/folke/noice.nvim/commit/3a23308e205f35fc2b80b93790fd3a92587d68e7)

I cannot reproduce either. I'm on a clean `.config` and `.local` (by changing the `XDG_` environment vars), using `minimal.lua`, even on those versions. `nui.nvim` and `nvim-notify` are latest. Can this be closed again, as p00f seemed to resolve their issue?

**Comment by MaMrEzO** [comment]
> Seems like you get E36 errors when we try to open a split. Not sure what triggers that.
> 
> Do you get the same with the default Noice config?

After a lot of plugin switches to figure out the cause of the error!
![Screenshot_20221016_202801](https://user-images.githubusercontent.com/1070230/196048184-38e2f2e4-e2ea-4932-a9c0-c94d5e846992.png)

I have `fgheng/winbar.nvim` installed, and there is a need to exclude some file types to `lua-bar` to not add a winbar to those buffers..., for example :
```lua
 disabled_filetypes = {
      statusline = {"NvimTree", "Outline"},
      winbar = {"NvimTree", "Outline"},
    },
```
Just removing `winbar` makes Noice work as expected..., but I cannot find the `ft` of CmdBar and Notify :)
