### ISSUE TITLE
bug: screen flicker when search witn incsearch on

### ISSUE THREAD

**Issue by jackielii** [folke/noice.nvim#679]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1954+g0a598c13b-Homebrew

### Operating system/version

macOS 14.0

### Describe the bug

I tried stable version of nvim v0.9.4, the issue is not here. With latest nightly, when search with `incsearch` on, and the word being searched NOT being on screen, the screen flickers

### Steps To Reproduce

1. `set incsearch`
2. search a word that's currently not on the screen

### Expected Behavior

No flicker.

Also I searched existing issues and seems #3 flickers in the search window, while this flicker is on the main buffer window

https://github.com/folke/noice.nvim/assets/360983/2c8db7b1-5b0b-4750-9aa6-ed6afba8b354

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "folke/noice.nvim",
    event = "VeryLazy",
    dependencies = {
      -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
      "MunifTanjim/nui.nvim",
      -- OPTIONAL:
      --   `nvim-notify` is only needed, if you want to use the notification view.
      --   If not available, we use `mini` as the fallback
      "rcarriga/nvim-notify",
    },
    opts = {
      presets = {
        bottom_search = true, -- use a classic bottom cmdline for search
        command_palette = false, -- position the cmdline and popupmenu together
        long_message_to_split = true, -- long messages will be sent to a split
        inc_rename = false, -- enables an input dialog for inc-rename.nvim
        lsp_doc_border = true, -- add a border to hover docs and signature help
      },
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

#### Screencast

re-recorded with repo.lua and example file:

https://github.com/folke/noice.nvim/assets/360983/8285f5a8-e396-4ef5-b824-ce4113d1a3cb

**Comment by roycrippen4** [comment]
I am also having the same issue.

**Comment by roycrippen4** [comment]
This issue should be closed. The flickering has stopped since the 0.9.5 release. This is likely an upstream issue and not an issue with noice.

**Comment by jackielii** [comment]
I can confirm this doesn't happen on latest HEAD anymore

**Comment by yifan0414** [comment]
Encountered the same issue on the Nightly version. When I `set nohlsearch`, flicker disappear.  If not, there will be.

**Comment by yifan0414** [comment]
disable noice back to noraml, reopen this issue?

**Comment by simeonoff** [comment]
Seems this issue is reproducible with `NVIM v0.10.0-dev-2699+gd6f406db4` on macOS.

**Comment by jackielii** [comment]
Yes, it's happening again

**Comment by yavorski** [comment]
Happening/Reproducible again with stable `v0.10` now.

**Comment by folke** [comment]
Will be fixed by https://github.com/neovim/neovim/pull/27950

**Comment by net** [comment]
I now get severe flickering of the hlsearch highlight itself when searching on the latest neovim master.

**Comment by folke** [comment]
Yeah, noticed that as well. Going back/forward with the cursor during substitute also doesnt work properly.
There's more work being done regarding these things in core. 
Hopefully that gets resolved soon

**Comment by net** [comment]
So is everyone on neovim 0.10 with noice just living with the flickers, or is there a workaround I'm missing?

**Comment by folke** [comment]
I only see the flickering when lsp progress is doing something. Besides that I dont see it

**Comment by folke** [comment]
I just pushed an update that should result in less flickering of hlsearch. Let me know if it helps!

**Comment by net** [comment]
Definitely seems much better with 4.0.1 and the latest neovim master! Thank you!

**Comment by unphased** [comment]
I believe this behavior shows under _**neovide**_ even more egregiously 

https://github.com/user-attachments/assets/0040c7c6-8b98-4620-b9b9-f684fb3a099d

Cannot use neovide with noice until this is fixed 🫠

**Comment by eyalz800** [comment]
I was able to workaround the issue with:
```lua
  if not vim.o.incsearch then
      return
  end
  vim.o.incsearch = false

  local ns = vim.api.nvim_create_namespace('noice-incsearch-ns')
  local group = vim.api.nvim_create_augroup('noice-incsearch-group', {})
  local start_pos = nil
  local matches = {}
  local cur_idx = 1
  local pat = ''
  local search_cmds = { ['/'] = true, ['?'] = true }
  local search_cmd = nil
  local accept = false

  vim.keymap.set('c', '<cr>', function()
      if search_cmd then
          accept = true
      end
      return '<cr>'
  end, { noremap = false, expr = true })

  local function get_matches(pattern)
      if pattern == '' then return {} end
      local result = {}
      local save_pos = vim.api.nvim_win_get_cursor(0)
      vim.api.nvim_win_set_cursor(0, { 1, 0 })

      while true do
          local pos = vim.fn.searchpos(pattern, 'W')
          local row, col = pos[1], pos[2]
          if row == 0 then break end
          table.insert(result, { row, col - 1 })
          if not pcall(vim.api.nvim_win_set_cursor, 0, { row, col }) then break end
          vim.api.nvim_win_set_cursor(0, { row, col })
      end

      vim.api.nvim_win_set_cursor(0, save_pos)
      return result
  end

  local function cursor_match_index()
      local best_match_idx = nil

      if search_cmd == '/' then
          for i, match in ipairs(matches) do
              local m_row, m_col = match[1], match[2]
              if m_row > start_pos[1] or (m_row == start_pos[1] and m_col >= start_pos[2]) then
                  best_match_idx = i
                  break
              end
          end
          if best_match_idx == nil then
              best_match_idx = 1
          end
      elseif search_cmd == '?' then
          for i = #matches, 1, -1 do
              local match = matches[i]
              local m_row, m_col = match[1], match[2]
              if m_row < start_pos[1] or (m_row == start_pos[1] and m_col < start_pos[2]) then
                  best_match_idx = i
                  break
              end
          end
          if best_match_idx == nil then
              best_match_idx = #matches
          end
      end

      return best_match_idx
  end

  local function highlight()
      vim.api.nvim_buf_clear_namespace(0, ns, 0, -1)
      for i, match in ipairs(matches) do
          local hl = (i == cur_idx) and 'IncSearch' or 'Search'
          vim.api.nvim_buf_set_extmark(0, ns, match[1] - 1, match[2], { hl_group = hl, end_col = match[2] + #pat })
      end
  end

  local function jump()
      local match = matches[cur_idx]
      if match then
          vim.api.nvim_win_set_cursor(0, { match[1], match[2] })
          vim.cmd('normal! zz')
      end
  end

  local function jump_final(cmd_type)
      if not accept then
          vim.api.nvim_win_set_cursor(0, start_pos)
          return
      end
      local match = matches[cur_idx]
      if match then
          local line = match[1]
          local col = match[2]
          if #matches > 1 then
              if search_cmd == '/' then
                  if col == 0 and line ~= 0 then
                      line = line - 1
                  else
                      col = col - 1
                  end
              elseif search_cmd == '?' then
                  if col ~= #(vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]) then
                      col = col + 1
                  else
                      if line + 1 <= vim.api.nvim_buf_line_count(0) then
                          line = line + 1
                      else
                          line = 1
                      end
                      col = 0
                  end
              end
          end
          vim.api.nvim_win_set_cursor(0, { line, col })
          vim.cmd('normal! zz')
      end
  end

  vim.api.nvim_create_autocmd('CmdlineEnter', {
      group = group,
      pattern = '/,?',
      callback = function()
          local cmd_type = vim.fn.getcmdtype()
          if search_cmds[cmd_type] == nil then return end
          start_pos = vim.api.nvim_win_get_cursor(0)
          accept = false
          matches = {}
          cur_idx = 1
          pat = ''
          search_cmd = cmd_type
      end,
  })

  vim.api.nvim_create_autocmd('CmdlineChanged', {
      group = group,
      pattern = '/,?',
      callback = function()
          if not search_cmd then return end
          pat = vim.fn.getcmdline()
          vim.fn.setreg('/', pat)

          matches = get_matches(pat)
          if #matches == 0 then
              vim.api.nvim_buf_clear_namespace(0, ns, 0, -1)
              return
          end

          cur_idx = cursor_match_index()
          jump()

          highlight()
      end,
  })

  vim.api.nvim_create_autocmd('CmdlineLeave', {
      group = group,
      pattern = '/,?',
      callback = function()
          if not search_cmd then return end
          vim.api.nvim_buf_clear_namespace(0, ns, 0, -1)
          jump_final()
          start_pos = nil
          accept = false
          matches = {}
          search_cmd = nil
      end,
  })
```

**Comment by OliverWich** [comment]
@unphased wrote:
> I believe this behavior shows under _**neovide**_ even more egregiously.
> Screen.Recording.2025-01-30.at.18.16.33.mp4
> 
> Cannot use neovide with incsearch and noice until this is fixed 🫠

Yes, this is still an issue!

It seems to happen when `wrapscan` and `incsearch` are both enabled, and the cursor is located _inside_ the last match of the buffer with the other matches not visible on screen.
It then jumps around wildly which NeoVide's scroll animations just show clearly in contrast to a raw nvim in a terminal where it just shows up as a flicker.

@folke Could we maybe get this re-opened and the fix from @eyalz800 (wow, my brain is melting, nice job, thanks!) evaluated and maybe integrated into noice?
It worked for me, but a clean fix inside noice itself seems better.

**Comment by lccanon** [comment]
I get the same issue with nvim 0.11.5 or 0.11.6 and noice 4.10.0. The flickering is perceptible but the search feature is still usable. The fix from @eyalz800 solves the issue.

**Comment by 89iuv** [comment]
Confirming that the issue is reproduced on my end with nvim: 0.11.6 and noice latest commit: 7bfd942.
Thank you @eyalz800 for the fix.
