### ISSUE TITLE
bug: search jumps back to original line on each character input

### ISSUE THREAD

**Issue by mikaraunio** [folke/noice.nvim#741]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2503+gda2130934-Homebrew

### Operating system/version

macOS 14.3.1 (23D60)

### Describe the bug

When searching, each time a character is entered the cursor shortly jumps back to the line it was on when the search was started. This causes the whole split to be redrawn if the original line is off-screen compared to the current match.

It almost feels like the search term was being emptied between keypresses.

### Steps To Reproduce

1. Start searching with `/` or `?`
2. Start entering a search term
3. The file will jump between the starting line and the line containing the match each time a character is entered

### Expected Behavior

I expected the search to behave like it does without noice.nvim, with no jumping around.

**Comment by mikaraunio** [comment]
Not stale.

**Comment by folke** [comment]
This is fixed for a recent Neovim nightly

**Comment by mikaraunio** [comment]
I'm seeing this again now. I'm currently on `v0.11.0-dev-1768+g9d699e2005-Homebrew`.

**Comment by gou4shi1** [comment]
same for me

**Comment by gou4shi1** [comment]
It should be introduced by https://github.com/folke/noice.nvim/commit/973e10a001b50087db5f101d66b367d945607a07

**Comment by owski** [comment]
I am still experiencing this issue.

```
❯ nvim --version
NVIM v0.11.1
Build type: Release
LuaJIT 2.1.1744318430
Run "nvim -V1 -v" for more info
```
OS: macOS 15.4.1

Config:

```lua
return {
	{
	 "folke/noice.nvim",
	 event = "VeryLazy",
	 opts = { },
	 dependencies = {
	    -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
	    "MunifTanjim/nui.nvim",
	    -- OPTIONAL:
	    --   `nvim-notify` is only needed, if you want to use the notification view.
	    --   If not available, we use `mini` as the fallback
	    "rcarriga/nvim-notify",
	},
    config = function()
        require("noice").setup({
            presets = {
                command_palette = true, -- position the cmdline and popupmenu together
            },
        })
    end
    }
}
```
