### ISSUE TITLE
Noice is partially broken on Nightly

### ISSUE THREAD

**Issue by folke** [folke/noice.nvim#998]
### Describe the bug

Some things currently don't work properly on nightly:

- [x] `confirm` messages are displayed too late (so not shown) 
- [x] `msg_show.return_prompt` should not be queued

### Related

- [x] https://github.com/neovim/neovim/pull/31224
- [x] https://github.com/folke/noice.nvim/commit/6e0c8dcc61282782ac7fa4b9b4b0c910fd3f83d9
- [x] https://github.com/neovim/neovim/pull/27874
- [x] https://github.com/folke/noice.nvim/issues/997

**Comment by b0o** [comment]
In https://github.com/folke/noice.nvim/issues/997#issuecomment-2478176747 you mentioned:

> The searching thing works for me with Snacks.notifier.
> nvim-notify has some issues with redraw.

However I just tried Snacks.notifier and seem to have the same issue there as well.

**Comment by folke** [comment]
What are the exact steps to reproduce?

**Comment by b0o** [comment]
In normal mode type `/foo<Cr>` where `foo` is some pattern which doesn't exist in the buffer. For me, the search input does not disappear after pressing `<Cr>`, until I press something like `j`, and then the search bar and "not found" notifications appear.

**Comment by folke** [comment]
@b0o I think what's causing this and probably just fixed it. Has probably something to do with `cmdheight` and `msg_show.return_prompt` ui messages.
Can you verify this issue at least is fixed for you with my changes?

**Comment by b0o** [comment]
Yes, both issues seem to be fixed now as of the latest nightly and the latest noice commits.

**Comment by folke** [comment]
Yep, seems like it. Great!

**Comment by augustocdias** [comment]
It seems the bug came back in nightly. Not only it is not showing a nice popup with buttons, it was replaced by this input that doesn't disappear after you confirm. When I tested in Neovide it seems the popup quickly shows and is replaced by this input... The input only disappears when I invoke a command. 

![tty](https://github.com/user-attachments/assets/8a0a9398-5d54-4531-9f97-7f455c396c9d)

**Comment by folke** [comment]
Yep, I'm aware. https://github.com/neovim/neovim/pull/31525

**Comment by folke** [comment]
I have this problem too. It's because of changes in Neovim. Feel free to provide a pr
